# ============================
# 1. BUILD STAGE
# ============================
FROM golang:1.24 AS builder

WORKDIR /app

# Copy dependency dulu
COPY go.mod go.sum ./
RUN go mod download

# Copy semua folder proyek
COPY . .

RUN rm -f .env

# Build binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server main.go


# ============================
# 2. RUN STAGE
# ============================
FROM alpine:3.19

WORKDIR /app

RUN apk add --no-cache tzdata ca-certificates

COPY --from=builder /app/server .

EXPOSE 9000

CMD ["./server"]
